#include <bits/stdc++.h>
#include <string>
#include <map>
#include <iostream>
#include <vector>
#define ll long long
#define Mx 1000000000
using namespace std;
int a[1000000];
int main()
{
    if (fopen("CAU5.INP", "r"))
    {
        freopen("CAU5.INP", "r", stdin);
        freopen("CAU5.OUT", "w", stdout);
    }
    map<string, int> mp;
    ios_base::sync_with_stdio(NULL);
    cin.tie(0);
    cout.tie(0);
    int n, k;
    cin >> n >> k;
    for (int i = 0; i < n; i++)
    {
        cin >> a[i];
    }
    for (int i = 0; i < n; i++)
    {
        for (int i = 0; i < k; i++)
        {
            if()
        }
    }